# Generated by Django 4.2.3 on 2023-08-09 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
