# Generated by Django 4.2.3 on 2023-08-09 11:55

import Olx_hardware_store.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwstoreuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Olx_hardware_store.accounts.validators.validate_isalpha]),
        ),
        migrations.AlterField(
            model_name='hwstoreuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Olx_hardware_store.accounts.validators.validate_isalpha]),
        ),
        migrations.AlterField(
            model_name='phonenumbersusermodel',
            name='phone',
            field=models.CharField(default=None, max_length=13, validators=[Olx_hardware_store.accounts.validators.validate_phone_number]),
        ),
    ]
