# Generated by Django 4.2.3 on 2023-08-09 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hwstoreuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwstoreuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
