# Generated by Django 4.2.3 on 2023-08-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hwstoreuser_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwstoreuser',
            name='age',
        ),
    ]
